{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.vault.enabled -}}
# HashiCorp Vault ClusterSecretStore for External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "kubetix.fullname" . }}-vault-backend
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.address | default "http://localhost:8200" | quote }}
      namespace: {{ .Values.externalSecrets.vault.namespace | default "default" }}
      path: {{ .Values.externalSecrets.vault.authPath | default "kubernetes" }}
      role: {{ .Values.externalSecrets.vault.role | quote }}
      kind: ClusterSecretStore
{{- end -}}
