{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.aws.enabled -}}
# AWS Secrets Manager External Secret via External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kubetix.fullname" . }}-aws
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "kubetix.fullname" . }}-aws-backend
    kind: SecretStore
  target:
    name: {{ include "kubetix.fullname" . }}-aws-secret
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretArn }}
        property: database-url
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.externalSecrets.aws.secretArn }}
        property: secret-key
{{- end -}}
