{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.vault.enabled -}}
# HashiCorp Vault External Secret via External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kubetix.fullname" . }}-vault
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "kubetix.fullname" . }}-vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "kubetix.fullname" . }}-vault-secret
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.externalSecrets.vault.secretPath }}
        property: database-url
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.externalSecrets.vault.secretPath }}
        property: secret-key
{{- end -}}
