{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.aws.enabled -}}
# AWS Secrets Manager SecretStore for External Secrets Operator
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "kubetix.fullname" . }}-aws-backend
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region | required ".Values.externalSecrets.aws.region is required when using AWS Secrets Manager" }}
      {{- if .Values.externalSecrets.aws.useIAMRole }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "kubetix.serviceAccountName" . }}
      {{- else if .Values.externalSecrets.aws.credentialsSecret }}
      authSecretRef:
        accessKeyId:
          name: {{ .Values.externalSecrets.aws.credentialsSecret }}
          key: {{ .Values.externalSecrets.aws.accessKeyIdKey | default "AWS_ACCESS_KEY_ID" }}
        secretAccessKey:
          name: {{ .Values.externalSecrets.aws.credentialsSecret }}
          key: {{ .Values.externalSecrets.aws.secretAccessKeyKey | default "AWS_SECRET_ACCESS_KEY" }}
      {{- end }}
{{- end -}}
