{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetix.oidcSecretName" . }}
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.oidc.clientSecret | quote }}
{{- end }}
