{{- if .Values.database.sqlite.enabled -}}
{{- $secretName := include "kubetix.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: sqlite:////app/data/kubetix.db
  secret-key: {{ randAlphaNum 32 | quote }}
{{- else if .Values.database.postgresql.enabled -}}
{{- $secretName := include "kubetix.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.database.postgresql.existingSecret }}
  database-url: {{ include "kubetix.databaseUrl" . }}
  {{- else }}
  database-url: postgresql://{{ .Values.database.postgresql.username }}:{{ .Values.database.postgresql.password }}@{{ .Values.database.postgresql.host }}:{{ .Values.database.postgresql.port }}/{{ .Values.database.postgresql.database }}
  {{- end }}
  secret-key: {{ randAlphaNum 32 | quote }}
{{- else }}
{{- fail "Please enable either database.sqlite.enabled or database.postgresql.enabled" }}
{{- end }}
