{{- if .Values.database.external.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubetix.databaseSecretName" . }}
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: postgresql://{{ .Values.database.external.username }}:{{ .Values.database.external.password }}@{{ .Values.database.external.host }}:{{ .Values.database.external.port }}/{{ .Values.database.external.database }}
{{- else if .Values.database.postgresql.enabled -}}
{{- $secretName := include "kubetix.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "kubetix.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: postgresql://{{ .Values.database.postgresql.auth.username }}:{{ .Values.database.postgresql.auth.password }}@{{ $secretName }}-postgresql:5432/{{ .Values.database.postgresql.auth.database }}
  secret-key: {{ randAlphaNum 32 | quote }}
{{- end }}
