apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubetix

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml

commonLabels:
  app: kubetix
  version: "0.1.0"

configMapGenerator:
  - name: kubetix-env
    literals:
      - MAX_GRANT_HOURS=720
      - DEFAULT_GRANT_HOURS=24

images:
  - name: ghcr.io/joryirving/kubetix-api
    newTag: latest
  - name: ghcr.io/joryirving/kubetix-web
    newTag: latest
