apiVersion: v1
kind: Secret
metadata:
  name: kubetix-secrets
  namespace: kubetix
type: Opaque
stringData:
  # Generate with: openssl rand -hex 32
  secret-key: change-me-in-production
  database-url: postgresql://kubetix:kubetix@kubetix-db:5432/kubetix
  # Database credentials
  db-username: kubetix
  db-password: kubetix
